### ISSUE TITLE
non-free license wrongly declared in Cargo.toml file

### ISSUE THREAD

**Issue by jonassmedegaard** [lienching/pci-ids.rs#17]
This project uses a custom derivative of the classic (Expat variant of) MIT license, which excludes use by military or law enforcement organisations.

That is wrongly declared in the file `Cargo.toml`, which simply says "MIT".

Please correct the cargo metadata to correctly reflect the restricted licensing (or even better: consider relicensing this project to use a more general public license commonly considered "free" by the free software and open source community).

**Comment by lienching** [comment]
Hi @jonassmedegaard ,
Thank you for pointing out the LICENSE term issue. I had fix the term to reflict just MIT.

**Comment by jonassmedegaard** [comment]
Great!

Thank you for choosing to release this under a free license - much appreciated!

In case you are curious: My interest is in packaging [cyme](https://lib.rs/crates/cyme) for distribution with Debian, and that project depends on this one.
