### ISSUE TITLE
Include pci.ids via submodule

### ISSUE THREAD

**Issue by mkroening** [lienching/pci-ids.rs#6]
pci.ids is available on GitHub: [pciutils/pciids](https://github.com/pciutils/pciids)

Have you considered including the file via a git submodule? That way, you could track changes to pci.ids more easily.

This is just a suggestion though, I am completely fine with the way pci.ids is currently included in this repository.

**Comment by lienching** [comment]
I think it is a good idea, I just push a commit to add the submodule
